SET(CTEST_PROJECT_NAME IRAD)
SET(CTEST_NIGHTLY_START_TIME "00:00:00 EST")
SET(CTEST_DROP_SITE_CDASH TRUE)

IF(NOT DEFINED CTEST_DROP_METHOD)
  SET(CTEST_DROP_METHOD "http")
ENDIF(NOT DEFINED CTEST_DROP_METHOD)

IF(CTEST_DROP_METHOD STREQUAL "http")
  SET(CTEST_DROP_SITE "ilrocstar13.incubator.illinois.edu")
  SET(CTEST_DROP_LOCATION "/CDash/submit.php?project=IRAD")
ENDIF(CTEST_DROP_METHOD STREQUAL "http")
  